### PR TITLE
docs: update README

### PR DESCRIPTION
**Pull request by takeshi-iwanari**
Signed-off-by: takeshi.iwanari <takeshi.iwanari@tier4.jp>

### CODE REVIEW

**Review by takam5f2 — APPROVED** [review]
LGTM!

**Comment by takam5f2** [comment]
@hsgwa  
Do you have any comment on this PR? Best,

**Comment by takam5f2** [comment]
@takeshi-iwanari  Please merge this PR after fixing picture as @hsgwa said :bowing_man:

**Comment by takeshi-iwanari** [comment]
We decided to use the current logo.

**Pull request merged**
